export interface BuildingRequest {
  name: string;
  street1: string;
  stNumber1: string;
  street2?: string;
  stNumber2?: string;
  city: string;
  region: string;
  postalCode: string;
  country: string;
  state: string;
  floors: number; 
  apartmentsNum: number;
  sqMetersTotal: string;
  sqMetersCommonSpaces: string;
  parkingExist: boolean;
  parkingSpacesNum: number;
  active: boolean;
  enable: boolean;
  buildingDescription?: string;
  undergroundFloorExist: boolean,
  halfFloorExist: boolean,
  overTopFloorExist:  boolean,
  managerHouseExist: boolean,
  storageExist: boolean,
  storageNum: number,
  managerId: number; 
  hasCentralHeating: boolean;
  heatingType?: string;
  heatingCapacityLitres?: number;
}
